# Generated by Django 5.1.3 on 2025-01-28 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("id_curso", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_curso", models.CharField(max_length=10, unique=True)),
                ("cantidad_estudiantes", models.IntegerField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                ("id_estudiante", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rut_estudiante",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("nombre_estudiante", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("direccion", models.CharField(blank=True, max_length=100, null=True)),
                ("correo", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                ("id_programa", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_programa", models.CharField(max_length=100)),
                ("cantidad_horas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Relator",
            fields=[
                ("id_relator", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rut_relator",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("nombre_relator", models.CharField(max_length=100)),
                (
                    "titulo_relator",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anios_experiencia", models.IntegerField(blank=True, null=True)),
                ("valor_hora", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CursoEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_curso",
                    models.ForeignKey(
                        db_column="id_curso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.curso",
                    ),
                ),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        db_column="id_estudiante",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.estudiante",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="estudiantes",
            field=models.ManyToManyField(
                through="app.CursoEstudiante", to="app.estudiante"
            ),
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                ("id_modulo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_modulo", models.CharField(max_length=100)),
                ("cantidad_horas", models.IntegerField()),
                (
                    "id_programa",
                    models.ForeignKey(
                        db_column="id_programa",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.programa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="id_programa",
            field=models.ForeignKey(
                db_column="id_programa",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.programa",
            ),
        ),
        migrations.CreateModel(
            name="ModuloRelator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_modulo",
                    models.ForeignKey(
                        db_column="id_modulo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.modulo",
                    ),
                ),
                (
                    "id_relator",
                    models.ForeignKey(
                        db_column="id_relator",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.relator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modulo",
            name="relatores",
            field=models.ManyToManyField(through="app.ModuloRelator", to="app.relator"),
        ),
    ]
