# Generated by Django 5.1.3 on 2024-12-03 20:42

from django.db import migrations
from django.db import transaction

class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    def seed_data(apps, schema_editor):
        with transaction.atomic():
            Autor = apps.get_model('biblioteca', 'Autor')
            Libro = apps.get_model('biblioteca', 'Libro')
            Genero = apps.get_model('biblioteca', 'Genero')

            # genera tres generos
            generos = [
                Genero(nombre='Ficción 2'),
                Genero(nombre='No Ficción 2'),
                Genero(nombre='Ciencia Ficción 2'),
            ]
            Genero.objects.bulk_create(generos)

            # crea 2 autores
            autores = [
                Autor(nombre='Stephen King', fecha_nacimiento='1947-09-21'),
                Autor(nombre='J.K. Rowling', fecha_nacimiento='1965-07-31'),
            ]
            Autor.objects.bulk_create(autores)

            # crea tres libros
            libros = [
                Libro(titulo='It', fecha_publicacion='1986-09-18', genero=generos[0]),
                Libro(titulo='Harry Potter y la piedra filosofal', fecha_publicacion='1997-06-26', genero=generos[1]),
                Libro(titulo='El código Da Vinci', fecha_publicacion='2003-02-18', genero=generos[2]),
            ]
            Libro.objects.bulk_create(libros)

            # Asignar autores a libros después de crearlos
            libros[0].autores.add(autores[0], autores[1])
            libros[1].autores.add(autores[1])
            libros[2].autores.add(autores[0])

    def reverse_seed_data(apps, schema_editor):
        Autor = apps.get_model('biblioteca', 'Autor')
        Libro = apps.get_model('biblioteca', 'Libro')
        Genero = apps.get_model('biblioteca', 'Genero')

        Libro.objects.all().delete()
        Autor.objects.all().delete()
        Genero.objects.all().delete()

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data)
    ]
