# Generated by Django 5.1.3 on 2024-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
    ]
