# Generated by Django 5.1.3 on 2024-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_categoria_etiqueta_producto_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="etiquetas",
            field=models.ManyToManyField(related_name="productos", to="myapp.etiqueta"),
        ),
    ]
