# Generated by Django 5.1.3 on 2024-12-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_producto_etiquetas"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
