# Generated by Django 5.1.3 on 2024-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_producto_created_at_producto_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[(1, 'DISPONIBLE'), (0, 'AGOTADO')], default=1, max_length=10),
        ),
    ]
