# Generated by Django 5.1.3 on 2024-11-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 1), ('AGOTADO', 0)], default='DISPONIBLE', max_length=10),
        ),
    ]
