# Generated by Django 5.1.3 on 2024-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Disponible'), (False, 'Agotado')], default=True),
        ),
    ]
