# Generated by Django 5.1.3 on 2024-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
